name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    
    - name: Lint with flake8
      run: |
        python -m flake8 --version
        # Only check for critical errors in the app directory
        python -m flake8 app/ --select=E9,F63,F7,F82 --show-source --statistics
    
    - name: Lint with ruff
      run: |
        ruff check .
        ruff format --check .
    
    - name: Type checking with mypy
      run: |
        mypy .
    
    - name: Run tests with coverage
      run: |
        pytest --cov=app --cov-report=term
    
    - name: Install package in development mode
      run: |
        pip install -e .[dev]

    - name: Build documentation
      run: |
        cd docs
        pip install -r requirements.txt
        make html
    
    - name: Upload documentation artifact
      if: success() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: docs/_build/html/
        retention-days: 5
